spring:
  application:
    name: piece

  datasource:
    url: jdbc:h2:mem:piece
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema.sql
      data-locations:
        - classpath:data.sql
      continue-on-error: false

logging:
  level:
    com.rxjang: debug