-- unit_cde 데이터 삽입
INSERT INTO unit_code (id, unit_code, name) VALUES (1, 'uc1572', '모수와 통계량 구별, 모집단과 표본');
INSERT INTO unit_code (id, unit_code, name) VALUES (2, 'uc1573', '도수분포표, 히스토그램, 도수분포다각형 작성 및 해석');
INSERT INTO unit_code (id, unit_code, name) VALUES (3, 'uc1574', '줄기-잎 그림 작성 및 해석');
INSERT INTO unit_code (id, unit_code, name) VALUES (4, 'uc1575', '막대그래프, 원 그래프');
INSERT INTO unit_code (id, unit_code, name) VALUES (5, 'uc1576', '중심 경향 척도 : 자료의 평균, 평균절대편차, 최빈값');
INSERT INTO unit_code (id, unit_code, name) VALUES (6, 'uc1577', '산포도 : 자료의 범위, 사분위수, IQR');
INSERT INTO unit_code (id, unit_code, name) VALUES (7, 'uc1578', '산포도 : 분산, 표준편차');
INSERT INTO unit_code (id, unit_code, name) VALUES (8, 'uc1579', '다변량 자료, 분할표, 산점도, 공분산과 상관계수');
INSERT INTO unit_code (id, unit_code, name) VALUES (9, 'uc1503', '합집합, 교집합 및 여집합');
INSERT INTO unit_code (id, unit_code, name) VALUES (10, 'uc1506', '사건의 합집합, 교집합 및 여집합의 계산');
INSERT INTO unit_code (id, unit_code, name) VALUES (11, 'uc1510', '기본 조건부 확률의 계산');
INSERT INTO unit_code (id, unit_code, name) VALUES (12, 'uc1513', '세 개 이상 집합의 교집합');
INSERT INTO unit_code (id, unit_code, name) VALUES (13, 'uc1519', '순열과 조합을 이용한 확률 계산');
INSERT INTO unit_code (id, unit_code, name) VALUES (14, 'uc1520', '이산확률분포, 이산확률변수, 확률질량함수');
INSERT INTO unit_code (id, unit_code, name) VALUES (15, 'uc1521', '연속확률분포, 연속확률변수, 확률밀도함수');
INSERT INTO unit_code (id, unit_code, name) VALUES (16, 'uc1523', '확률변수의 기대값');
INSERT INTO unit_code (id, unit_code, name) VALUES (17, 'uc1524', '확률변수의 분산, 표준편차');
INSERT INTO unit_code (id, unit_code, name) VALUES (18, 'uc1570', '확률변수의 공분산과 상관계수');
INSERT INTO unit_code (id, unit_code, name) VALUES (19, 'uc1526', '결합확률밀도함수');
INSERT INTO unit_code (id, unit_code, name) VALUES (20, 'uc1529', '확률변수의 독립과 종속 여부 판단');
INSERT INTO unit_code (id, unit_code, name) VALUES (21, 'uc1534', '이항분포 기본 계산, 이항분포의 평균 및 표준 편차');
INSERT INTO unit_code (id, unit_code, name) VALUES (22, 'uc1535', '이항 공식, 이항분포를 사용하여 정확히 m번 성공할 확률 찾기');
INSERT INTO unit_code (id, unit_code, name) VALUES (23, 'uc1536', '이항 공식, 이항분포를 사용하여 m번 이상 또는 미만 성공할 확률 찾기');
INSERT INTO unit_code (id, unit_code, name) VALUES (24, 'uc1537', '비복원추출, 초기하분포, 초기하확률');
INSERT INTO unit_code (id, unit_code, name) VALUES (25, 'uc1539', '정규분포, 정규분포의 확률밀도함수, 정규분포의 확률 계산');
INSERT INTO unit_code (id, unit_code, name) VALUES (26, 'uc1540', '표준정규분포의  확률 계산하기');
INSERT INTO unit_code (id, unit_code, name) VALUES (27, 'uc1541', '중심극한정리 : 표본 평균의 표본 분포');
INSERT INTO unit_code (id, unit_code, name) VALUES (28, 'uc1542', '중심극한정리 : 이항 분포에 대한 정규 근사');
INSERT INTO unit_code (id, unit_code, name) VALUES (29, 'uc1548', '모평균에 대한 신뢰구간');
INSERT INTO unit_code (id, unit_code, name) VALUES (30, 'uc1564', 'F분포');
INSERT INTO unit_code (id, unit_code, name) VALUES (31, 'uc1568', '카이제곱분포, 자유도, 표본분산, 카이제곱 검정');
INSERT INTO unit_code (id, unit_code, name) VALUES (32, 'uc1580', '표본추출 : 단순랜덤추출');
INSERT INTO unit_code (id, unit_code, name) VALUES (33, 'uc1581', '표본추출 : 계통추출법');
INSERT INTO unit_code (id, unit_code, name) VALUES (34, 'uc1582', '표본추출 : 표집틀(sampling frame)');
INSERT INTO unit_code (id, unit_code, name) VALUES (35, 'uc1583', '실험단위, 인자, 반응변수, 처리');
INSERT INTO unit_code (id, unit_code, name) VALUES (36, 'uc1584', '랜덤화, 블록화, 랜덤블록계획, 반복');
INSERT INTO unit_code (id, unit_code, name) VALUES (37, 'uc1571', 'SAS 명령어, 함수');


-- problem 데이터 삽입
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1001, 'uc1580', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1002, 'uc1580', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1003, 'uc1580', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1004, 'uc1580', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1005, 'uc1580', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1006, 'uc1581', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1007, 'uc1581', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1008, 'uc1581', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1009, 'uc1581', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1013, 'uc1582', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1014, 'uc1582', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1016, 'uc1583', 3, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1017, 'uc1583', 3, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1018, 'uc1583', 3, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1021, 'uc1583', 3, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1022, 'uc1583', 3, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1023, 'uc1583', 3, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1024, 'uc1583', 3, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1031, 'uc1584', 3, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1032, 'uc1584', 3, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1033, 'uc1584', 3, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1034, 'uc1584', 3, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1036, 'uc1583', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1037, 'uc1583', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1038, 'uc1583', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1046, 'uc1584', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1047, 'uc1584', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1048, 'uc1584', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1051, 'uc1576', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1052, 'uc1576', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1053, 'uc1576', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1056, 'uc1523', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1057, 'uc1523', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1058, 'uc1523', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1061, 'uc1578', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1062, 'uc1578', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1063, 'uc1578', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1066, 'uc1579', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1067, 'uc1579', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1068, 'uc1579', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1071, 'uc1575', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1072, 'uc1575', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1073, 'uc1575', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1074, 'uc1575', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1076, 'uc1573', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1077, 'uc1573', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1078, 'uc1573', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1081, 'uc1579', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1082, 'uc1579', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1083, 'uc1579', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1086, 'uc1576', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1087, 'uc1576', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1088, 'uc1576', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1091, 'uc1577', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1092, 'uc1577', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1093, 'uc1577', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1096, 'uc1579', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1097, 'uc1579', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1098, 'uc1579', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1111, 'uc1572', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1112, 'uc1572', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1113, 'uc1572', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1116, 'uc1572', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1117, 'uc1572', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1118, 'uc1572', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1121, 'uc1576', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1122, 'uc1576', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1123, 'uc1576', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1126, 'uc1573', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1127, 'uc1573', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1128, 'uc1573', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1136, 'uc1576', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1137, 'uc1576', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1138, 'uc1576', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1141, 'uc1574', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1142, 'uc1574', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1143, 'uc1574', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1146, 'uc1576', 2, 'SELECTION', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1147, 'uc1576', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1148, 'uc1576', 2, 'SELECTION', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1151, 'uc1575', 2, 'SELECTION', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1152, 'uc1575', 2, 'SELECTION', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1153, 'uc1575', 2, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1156, 'uc1573', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1157, 'uc1573', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1158, 'uc1573', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1161, 'uc1573', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1162, 'uc1573', 2, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1163, 'uc1573', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1171, 'uc1579', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1172, 'uc1579', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1173, 'uc1579', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1176, 'uc1579', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1177, 'uc1579', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1178, 'uc1579', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1181, 'uc1577', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1182, 'uc1577', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1183, 'uc1577', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1186, 'uc1576', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1187, 'uc1576', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1188, 'uc1576', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1191, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1192, 'uc1537', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1193, 'uc1537', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1196, 'uc1520', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1197, 'uc1520', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1198, 'uc1520', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1201, 'uc1510', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1202, 'uc1510', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1203, 'uc1510', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1206, 'uc1510', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1207, 'uc1510', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1208, 'uc1510', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1211, 'uc1513', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1212, 'uc1513', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1213, 'uc1513', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1216, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1217, 'uc1529', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1218, 'uc1529', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1221, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1222, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1223, 'uc1537', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1226, 'uc1521', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1227, 'uc1521', 4, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1228, 'uc1521', 4, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1231, 'uc1523', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1232, 'uc1523', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1233, 'uc1523', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1236, 'uc1523', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1237, 'uc1523', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1238, 'uc1523', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1241, 'uc1523', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1242, 'uc1523', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1243, 'uc1523', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1246, 'uc1523', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1247, 'uc1524', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1248, 'uc1523', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1251, 'uc1523', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1252, 'uc1523', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1253, 'uc1523', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1256, 'uc1526', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1257, 'uc1526', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1258, 'uc1526', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1261, 'uc1526', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1262, 'uc1526', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1263, 'uc1526', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1266, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1267, 'uc1529', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1268, 'uc1529', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1271, 'uc1570', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1272, 'uc1570', 2, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1273, 'uc1570', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1276, 'uc1510', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1277, 'uc1510', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1278, 'uc1510', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1281, 'uc1535', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1282, 'uc1535', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1283, 'uc1535', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1286, 'uc1510', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1287, 'uc1510', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1288, 'uc1510', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1291, 'uc1510', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1292, 'uc1510', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1293, 'uc1510', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1296, 'uc1506', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1297, 'uc1506', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1298, 'uc1506', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1301, 'uc1503', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1302, 'uc1503', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1303, 'uc1503', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1306, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1307, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1308, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1311, 'uc1523', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1312, 'uc1523', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1313, 'uc1523', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1316, 'uc1534', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1317, 'uc1534', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1318, 'uc1534', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1321, 'uc1521', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1322, 'uc1521', 4, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1323, 'uc1521', 4, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1326, 'uc1521', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1327, 'uc1521', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1328, 'uc1521', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1331, 'uc1523', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1332, 'uc1523', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1333, 'uc1523', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1336, 'uc1526', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1337, 'uc1526', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1338, 'uc1526', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1341, 'uc1526', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1342, 'uc1526', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1343, 'uc1526', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1346, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1347, 'uc1529', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1348, 'uc1529', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1351, 'uc1571', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1356, 'uc1571', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1361, 'uc1534', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1362, 'uc1534', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1363, 'uc1534', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1366, 'uc1540', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1367, 'uc1540', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1368, 'uc1540', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1371, 'uc1540', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1372, 'uc1540', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1373, 'uc1540', 2, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1376, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1377, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1378, 'uc1539', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1381, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1382, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1383, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1386, 'uc1520', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1387, 'uc1520', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1388, 'uc1520', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1391, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1392, 'uc1537', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1393, 'uc1537', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1396, 'uc1535', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1397, 'uc1535', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1398, 'uc1535', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1401, 'uc1536', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1402, 'uc1536', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1403, 'uc1536', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1406, 'uc1541', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1407, 'uc1541', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1408, 'uc1541', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1411, 'uc1542', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1412, 'uc1542', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1413, 'uc1542', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1416, 'uc1519', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1417, 'uc1519', 2, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1418, 'uc1519', 2, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1421, 'uc1540', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1422, 'uc1540', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1423, 'uc1540', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1426, 'uc1540', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1427, 'uc1540', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1428, 'uc1540', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1431, 'uc1539', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1432, 'uc1539', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1433, 'uc1539', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1436, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1437, 'uc1539', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1438, 'uc1539', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1441, 'uc1541', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1442, 'uc1541', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1443, 'uc1541', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1446, 'uc1539', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1447, 'uc1539', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1448, 'uc1539', 4, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1451, 'uc1520', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1452, 'uc1520', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1453, 'uc1520', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1456, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1457, 'uc1537', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1458, 'uc1537', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1461, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1462, 'uc1537', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1463, 'uc1537', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1466, 'uc1536', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1467, 'uc1536', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1468, 'uc1536', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1471, 'uc1536', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1472, 'uc1536', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1473, 'uc1536', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1476, 'uc1534', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1477, 'uc1534', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1478, 'uc1534', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1481, 'uc1536', 5, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1482, 'uc1536', 5, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1483, 'uc1536', 5, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1486, 'uc1542', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1487, 'uc1542', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1488, 'uc1542', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1491, 'uc1542', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1492, 'uc1542', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1493, 'uc1542', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1496, 'uc1541', 4, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1497, 'uc1541', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1498, 'uc1541', 4, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1501, 'uc1568', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1502, 'uc1568', 4, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1503, 'uc1568', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1506, 'uc1564', 4, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1507, 'uc1564', 4, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1508, 'uc1564', 4, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1511, 'uc1564', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1512, 'uc1564', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1513, 'uc1564', 3, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1516, 'uc1571', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1517, 'uc1571', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1518, 'uc1571', 3, 'SUBJECTIVE', '2');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1521, 'uc1571', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1522, 'uc1571', 3, 'SUBJECTIVE', '3');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1523, 'uc1571', 3, 'SUBJECTIVE', '4');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1526, 'uc1571', 2, 'SUBJECTIVE', '1');
INSERT INTO problem (id, unit_code, level, problem_type, answer) VALUES (1531, 'uc1548', 3, 'SELECTION', '2');