package com.rxjang.piece.infrastructure.persistance.repository

import com.rxjang.piece.infrastructure.persistance.entity.ProblemScoringEntity
import com.rxjang.piece.infrastructure.persistance.entity.ProblemScoringId
import com.rxjang.piece.infrastructure.persistance.repository.custom.ProblemScoringRepositoryCustom
import org.springframework.data.jpa.repository.JpaRepository

interface ProblemScoringRepository: JpaRepository<ProblemScoringEntity, ProblemScoringId>, ProblemScoringRepositoryCustom